/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppReviewRouteImport } from './routes/_app.review'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppInvestigationsRouteImport } from './routes/_app.investigations'
import { Route as AppIntakeRouteImport } from './routes/_app.intake'
import { Route as AppImagingRouteImport } from './routes/_app.imaging'
import { Route as AppExplainabilityRouteImport } from './routes/_app.explainability'
import { Route as AppEvidenceRouteImport } from './routes/_app.evidence'
import { Route as AppDifferentialRouteImport } from './routes/_app.differential'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCopilotRouteImport } from './routes/_app.copilot'
import { Route as AppConfidenceRouteImport } from './routes/_app.confidence'
import { Route as AppComparisonRouteImport } from './routes/_app.comparison'
import { Route as AppCommandCenterRouteImport } from './routes/_app.command-center'
import { Route as AppArchitectureRouteImport } from './routes/_app.architecture'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppNurseQueueRouteImport } from './routes/_app.nurse.queue'
import { Route as AppNurseIntakeRouteImport } from './routes/_app.nurse.intake'
import { Route as AppNurseDashboardRouteImport } from './routes/_app.nurse.dashboard'
import { Route as AppDoctorReviewRouteImport } from './routes/_app.doctor.review'
import { Route as AppDoctorDashboardRouteImport } from './routes/_app.doctor.dashboard'
import { Route as AppDoctorApprovalsRouteImport } from './routes/_app.doctor.approvals'
import { Route as AppDoctorReportLatestRouteImport } from './routes/_app.doctor.report.latest'
import { Route as AppDoctorReportIntakeIdRouteImport } from './routes/_app.doctor.report.$intakeId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationsRoute = AppInvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeRoute = AppIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AppRoute,
} as any)
const AppImagingRoute = AppImagingRouteImport.update({
  id: '/imaging',
  path: '/imaging',
  getParentRoute: () => AppRoute,
} as any)
const AppExplainabilityRoute = AppExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppDifferentialRoute = AppDifferentialRouteImport.update({
  id: '/differential',
  path: '/differential',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppConfidenceRoute = AppConfidenceRouteImport.update({
  id: '/confidence',
  path: '/confidence',
  getParentRoute: () => AppRoute,
} as any)
const AppComparisonRoute = AppComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandCenterRoute = AppCommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => AppRoute,
} as any)
const AppArchitectureRoute = AppArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppNurseQueueRoute = AppNurseQueueRouteImport.update({
  id: '/nurse/queue',
  path: '/nurse/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppNurseIntakeRoute = AppNurseIntakeRouteImport.update({
  id: '/nurse/intake',
  path: '/nurse/intake',
  getParentRoute: () => AppRoute,
} as any)
const AppNurseDashboardRoute = AppNurseDashboardRouteImport.update({
  id: '/nurse/dashboard',
  path: '/nurse/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorReviewRoute = AppDoctorReviewRouteImport.update({
  id: '/doctor/review',
  path: '/doctor/review',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorDashboardRoute = AppDoctorDashboardRouteImport.update({
  id: '/doctor/dashboard',
  path: '/doctor/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorApprovalsRoute = AppDoctorApprovalsRouteImport.update({
  id: '/doctor/approvals',
  path: '/doctor/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorReportLatestRoute = AppDoctorReportLatestRouteImport.update({
  id: '/doctor/report/latest',
  path: '/doctor/report/latest',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorReportIntakeIdRoute = AppDoctorReportIntakeIdRouteImport.update({
  id: '/doctor/report/$intakeId',
  path: '/doctor/report/$intakeId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/architecture': typeof AppArchitectureRoute
  '/command-center': typeof AppCommandCenterRoute
  '/comparison': typeof AppComparisonRoute
  '/confidence': typeof AppConfidenceRoute
  '/copilot': typeof AppCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/differential': typeof AppDifferentialRoute
  '/evidence': typeof AppEvidenceRoute
  '/explainability': typeof AppExplainabilityRoute
  '/imaging': typeof AppImagingRoute
  '/intake': typeof AppIntakeRoute
  '/investigations': typeof AppInvestigationsRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/review': typeof AppReviewRoute
  '/search': typeof AppSearchRoute
  '/doctor/approvals': typeof AppDoctorApprovalsRoute
  '/doctor/dashboard': typeof AppDoctorDashboardRoute
  '/doctor/review': typeof AppDoctorReviewRoute
  '/nurse/dashboard': typeof AppNurseDashboardRoute
  '/nurse/intake': typeof AppNurseIntakeRoute
  '/nurse/queue': typeof AppNurseQueueRoute
  '/doctor/report/$intakeId': typeof AppDoctorReportIntakeIdRoute
  '/doctor/report/latest': typeof AppDoctorReportLatestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/architecture': typeof AppArchitectureRoute
  '/command-center': typeof AppCommandCenterRoute
  '/comparison': typeof AppComparisonRoute
  '/confidence': typeof AppConfidenceRoute
  '/copilot': typeof AppCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/differential': typeof AppDifferentialRoute
  '/evidence': typeof AppEvidenceRoute
  '/explainability': typeof AppExplainabilityRoute
  '/imaging': typeof AppImagingRoute
  '/intake': typeof AppIntakeRoute
  '/investigations': typeof AppInvestigationsRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/review': typeof AppReviewRoute
  '/search': typeof AppSearchRoute
  '/doctor/approvals': typeof AppDoctorApprovalsRoute
  '/doctor/dashboard': typeof AppDoctorDashboardRoute
  '/doctor/review': typeof AppDoctorReviewRoute
  '/nurse/dashboard': typeof AppNurseDashboardRoute
  '/nurse/intake': typeof AppNurseIntakeRoute
  '/nurse/queue': typeof AppNurseQueueRoute
  '/doctor/report/$intakeId': typeof AppDoctorReportIntakeIdRoute
  '/doctor/report/latest': typeof AppDoctorReportLatestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/architecture': typeof AppArchitectureRoute
  '/_app/command-center': typeof AppCommandCenterRoute
  '/_app/comparison': typeof AppComparisonRoute
  '/_app/confidence': typeof AppConfidenceRoute
  '/_app/copilot': typeof AppCopilotRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/differential': typeof AppDifferentialRoute
  '/_app/evidence': typeof AppEvidenceRoute
  '/_app/explainability': typeof AppExplainabilityRoute
  '/_app/imaging': typeof AppImagingRoute
  '/_app/intake': typeof AppIntakeRoute
  '/_app/investigations': typeof AppInvestigationsRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/doctor/approvals': typeof AppDoctorApprovalsRoute
  '/_app/doctor/dashboard': typeof AppDoctorDashboardRoute
  '/_app/doctor/review': typeof AppDoctorReviewRoute
  '/_app/nurse/dashboard': typeof AppNurseDashboardRoute
  '/_app/nurse/intake': typeof AppNurseIntakeRoute
  '/_app/nurse/queue': typeof AppNurseQueueRoute
  '/_app/doctor/report/$intakeId': typeof AppDoctorReportIntakeIdRoute
  '/_app/doctor/report/latest': typeof AppDoctorReportLatestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/architecture'
    | '/command-center'
    | '/comparison'
    | '/confidence'
    | '/copilot'
    | '/dashboard'
    | '/differential'
    | '/evidence'
    | '/explainability'
    | '/imaging'
    | '/intake'
    | '/investigations'
    | '/knowledge'
    | '/review'
    | '/search'
    | '/doctor/approvals'
    | '/doctor/dashboard'
    | '/doctor/review'
    | '/nurse/dashboard'
    | '/nurse/intake'
    | '/nurse/queue'
    | '/doctor/report/$intakeId'
    | '/doctor/report/latest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/architecture'
    | '/command-center'
    | '/comparison'
    | '/confidence'
    | '/copilot'
    | '/dashboard'
    | '/differential'
    | '/evidence'
    | '/explainability'
    | '/imaging'
    | '/intake'
    | '/investigations'
    | '/knowledge'
    | '/review'
    | '/search'
    | '/doctor/approvals'
    | '/doctor/dashboard'
    | '/doctor/review'
    | '/nurse/dashboard'
    | '/nurse/intake'
    | '/nurse/queue'
    | '/doctor/report/$intakeId'
    | '/doctor/report/latest'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/admin'
    | '/_app/architecture'
    | '/_app/command-center'
    | '/_app/comparison'
    | '/_app/confidence'
    | '/_app/copilot'
    | '/_app/dashboard'
    | '/_app/differential'
    | '/_app/evidence'
    | '/_app/explainability'
    | '/_app/imaging'
    | '/_app/intake'
    | '/_app/investigations'
    | '/_app/knowledge'
    | '/_app/review'
    | '/_app/search'
    | '/_app/doctor/approvals'
    | '/_app/doctor/dashboard'
    | '/_app/doctor/review'
    | '/_app/nurse/dashboard'
    | '/_app/nurse/intake'
    | '/_app/nurse/queue'
    | '/_app/doctor/report/$intakeId'
    | '/_app/doctor/report/latest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investigations': {
      id: '/_app/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof AppInvestigationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intake': {
      id: '/_app/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AppIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imaging': {
      id: '/_app/imaging'
      path: '/imaging'
      fullPath: '/imaging'
      preLoaderRoute: typeof AppImagingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explainability': {
      id: '/_app/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof AppExplainabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidence': {
      id: '/_app/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/differential': {
      id: '/_app/differential'
      path: '/differential'
      fullPath: '/differential'
      preLoaderRoute: typeof AppDifferentialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copilot': {
      id: '/_app/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/confidence': {
      id: '/_app/confidence'
      path: '/confidence'
      fullPath: '/confidence'
      preLoaderRoute: typeof AppConfidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comparison': {
      id: '/_app/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof AppComparisonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/command-center': {
      id: '/_app/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AppCommandCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/architecture': {
      id: '/_app/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof AppArchitectureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nurse/queue': {
      id: '/_app/nurse/queue'
      path: '/nurse/queue'
      fullPath: '/nurse/queue'
      preLoaderRoute: typeof AppNurseQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nurse/intake': {
      id: '/_app/nurse/intake'
      path: '/nurse/intake'
      fullPath: '/nurse/intake'
      preLoaderRoute: typeof AppNurseIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nurse/dashboard': {
      id: '/_app/nurse/dashboard'
      path: '/nurse/dashboard'
      fullPath: '/nurse/dashboard'
      preLoaderRoute: typeof AppNurseDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor/review': {
      id: '/_app/doctor/review'
      path: '/doctor/review'
      fullPath: '/doctor/review'
      preLoaderRoute: typeof AppDoctorReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor/dashboard': {
      id: '/_app/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof AppDoctorDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor/approvals': {
      id: '/_app/doctor/approvals'
      path: '/doctor/approvals'
      fullPath: '/doctor/approvals'
      preLoaderRoute: typeof AppDoctorApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor/report/latest': {
      id: '/_app/doctor/report/latest'
      path: '/doctor/report/latest'
      fullPath: '/doctor/report/latest'
      preLoaderRoute: typeof AppDoctorReportLatestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor/report/$intakeId': {
      id: '/_app/doctor/report/$intakeId'
      path: '/doctor/report/$intakeId'
      fullPath: '/doctor/report/$intakeId'
      preLoaderRoute: typeof AppDoctorReportIntakeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppArchitectureRoute: typeof AppArchitectureRoute
  AppCommandCenterRoute: typeof AppCommandCenterRoute
  AppComparisonRoute: typeof AppComparisonRoute
  AppConfidenceRoute: typeof AppConfidenceRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDifferentialRoute: typeof AppDifferentialRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppExplainabilityRoute: typeof AppExplainabilityRoute
  AppImagingRoute: typeof AppImagingRoute
  AppIntakeRoute: typeof AppIntakeRoute
  AppInvestigationsRoute: typeof AppInvestigationsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSearchRoute: typeof AppSearchRoute
  AppDoctorApprovalsRoute: typeof AppDoctorApprovalsRoute
  AppDoctorDashboardRoute: typeof AppDoctorDashboardRoute
  AppDoctorReviewRoute: typeof AppDoctorReviewRoute
  AppNurseDashboardRoute: typeof AppNurseDashboardRoute
  AppNurseIntakeRoute: typeof AppNurseIntakeRoute
  AppNurseQueueRoute: typeof AppNurseQueueRoute
  AppDoctorReportIntakeIdRoute: typeof AppDoctorReportIntakeIdRoute
  AppDoctorReportLatestRoute: typeof AppDoctorReportLatestRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppArchitectureRoute: AppArchitectureRoute,
  AppCommandCenterRoute: AppCommandCenterRoute,
  AppComparisonRoute: AppComparisonRoute,
  AppConfidenceRoute: AppConfidenceRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDifferentialRoute: AppDifferentialRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppExplainabilityRoute: AppExplainabilityRoute,
  AppImagingRoute: AppImagingRoute,
  AppIntakeRoute: AppIntakeRoute,
  AppInvestigationsRoute: AppInvestigationsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppReviewRoute: AppReviewRoute,
  AppSearchRoute: AppSearchRoute,
  AppDoctorApprovalsRoute: AppDoctorApprovalsRoute,
  AppDoctorDashboardRoute: AppDoctorDashboardRoute,
  AppDoctorReviewRoute: AppDoctorReviewRoute,
  AppNurseDashboardRoute: AppNurseDashboardRoute,
  AppNurseIntakeRoute: AppNurseIntakeRoute,
  AppNurseQueueRoute: AppNurseQueueRoute,
  AppDoctorReportIntakeIdRoute: AppDoctorReportIntakeIdRoute,
  AppDoctorReportLatestRoute: AppDoctorReportLatestRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
