"""
PRATHAM Demo Library Patient Profiles
Contains 10 curated emergency cases with complete patient telemetry.
"""

DEMO_CASES = {
    "healthy": {
        "id": "healthy",
        "name": "Healthy Adult Checkup",
        "age": 28,
        "sex": "female",
        "chief_complaint": "Routine health screening and baseline ECG.",
        "vitals": {"hr": 72, "bp": "118/76", "spo2": 99, "rr": 14, "temp": 36.8},
        "symptoms": {"chest_pain": False, "breathlessness": False, "trauma": False, "bleeding": False, "unconsciousness": False, "neurological": False},
        "top_condition": "Healthy Baseline Assessment",
        "confidence": "HIGH",
    },
    "routine": {
        "id": "routine",
        "name": "Routine Checkup Baseline",
        "age": 45,
        "sex": "male",
        "chief_complaint": "Annual physical checkup, minor seasonal cough.",
        "vitals": {"hr": 78, "bp": "122/80", "spo2": 98, "rr": 16, "temp": 37.0},
        "symptoms": {"chest_pain": False, "breathlessness": False, "trauma": False, "bleeding": False, "unconsciousness": False, "neurological": False},
        "top_condition": "Routine Checkup Baseline",
        "confidence": "HIGH",
    },
    "pneumonia": {
        "id": "pneumonia",
        "name": "Community Acquired Pneumonia",
        "age": 62,
        "sex": "male",
        "chief_complaint": "Progressive dyspnea, high fever, productive rust-colored sputum.",
        "vitals": {"hr": 104, "bp": "112/68", "spo2": 91, "rr": 24, "temp": 38.9},
        "symptoms": {"chest_pain": False, "breathlessness": True, "trauma": False, "bleeding": False, "unconsciousness": False, "neurological": False},
        "top_condition": "Community-Acquired Pneumonia",
        "confidence": "HIGH",
    },
    "acs": {
        "id": "acs",
        "name": "Acute Coronary Syndrome",
        "age": 58,
        "sex": "male",
        "chief_complaint": "Crushing substernal chest pain radiating to left arm/jaw, diaphoresis.",
        "vitals": {"hr": 112, "bp": "98/60", "spo2": 94, "rr": 20, "temp": 37.1},
        "symptoms": {"chest_pain": True, "breathlessness": True, "trauma": False, "bleeding": False, "unconsciousness": False, "neurological": False},
        "top_condition": "Acute Coronary Syndrome",
        "confidence": "HIGH",
    },
    "stroke": {
        "id": "stroke",
        "name": "Acute Ischemic Stroke",
        "age": 71,
        "sex": "female",
        "chief_complaint": "Sudden onset left-sided facial droop, arm drift, and slurred speech.",
        "vitals": {"hr": 88, "bp": "178/96", "spo2": 97, "rr": 18, "temp": 36.6},
        "symptoms": {"chest_pain": False, "breathlessness": False, "trauma": False, "bleeding": False, "unconsciousness": False, "neurological": True},
        "top_condition": "Acute Ischemic Stroke",
        "confidence": "HIGH",
    },
    "pe": {
        "id": "pe",
        "name": "Pulmonary Embolism",
        "age": 42,
        "sex": "female",
        "chief_complaint": "Sudden onset severe pleuritic chest pain, tachypnea, swelling in right calf.",
        "vitals": {"hr": 118, "bp": "110/72", "spo2": 89, "rr": 28, "temp": 37.3},
        "symptoms": {"chest_pain": True, "breathlessness": True, "trauma": False, "bleeding": False, "unconsciousness": False, "neurological": False},
        "top_condition": "Pulmonary Embolism",
        "confidence": "HIGH",
    },
    "sepsis": {
        "id": "sepsis",
        "name": "Sepsis & Septic Shock",
        "age": 69,
        "sex": "male",
        "chief_complaint": "Extreme weakness, shivering, altered mental status, suspected UTI.",
        "vitals": {"hr": 124, "bp": "86/52", "spo2": 93, "rr": 26, "temp": 39.2},
        "symptoms": {"chest_pain": False, "breathlessness": True, "trauma": False, "bleeding": False, "unconsciousness": True, "neurological": False},
        "top_condition": "Sepsis & Septic Shock",
        "confidence": "HIGH",
    },
    "polytrauma": {
        "id": "polytrauma",
        "name": "Polytrauma / Hemorrhagic Shock",
        "age": 31,
        "sex": "male",
        "chief_complaint": "MVC. Fractured femur, abdominal tenderness, severe active bleeding.",
        "vitals": {"hr": 138, "bp": "78/40", "spo2": 92, "rr": 30, "temp": 35.8},
        "symptoms": {"chest_pain": False, "breathlessness": True, "trauma": True, "bleeding": True, "unconsciousness": True, "neurological": False},
        "top_condition": "Hemorragic Shock",
        "confidence": "HIGH",
    },
    "dka": {
        "id": "dka",
        "name": "Diabetic Ketoacidosis (DKA)",
        "age": 24,
        "sex": "female",
        "chief_complaint": "Nausea, vomiting, deep rapid breathing (Kussmaul), fruity odor on breath.",
        "vitals": {"hr": 115, "bp": "105/65", "spo2": 98, "rr": 26, "temp": 37.2},
        "symptoms": {"chest_pain": False, "breathlessness": True, "trauma": False, "bleeding": False, "unconsciousness": True, "neurological": False},
        "top_condition": "Diabetic Ketoacidosis (DKA)",
        "confidence": "HIGH",
    },
    "heart_failure": {
        "id": "heart_failure",
        "name": "Acute Decompensated Heart Failure",
        "age": 75,
        "sex": "female",
        "chief_complaint": "Severe orthopnea, paroxysmal nocturnal dyspnea, bilateral pitting ankle edema.",
        "vitals": {"hr": 96, "bp": "145/88", "spo2": 87, "rr": 24, "temp": 36.9},
        "symptoms": {"chest_pain": False, "breathlessness": True, "trauma": False, "bleeding": False, "unconsciousness": False, "neurological": False},
        "top_condition": "Acute Decompensated Heart Failure",
        "confidence": "HIGH",
    },
}
